### ISSUE TITLE
Pilot a workflow model for managing ClinVar variations 

### ISSUE THREAD

**Issue by KelseaChang5** [clingen-data-model/clinvar-curation-input-tool#27]
First steps before specific reports are developed:

Involves: 
- [x] Creating a mock up report @KelseaChang5 
- [ ] Present mock up to stakeholders on Wednesday, March 9th during the ClinGen Broad Weekly Meeting at 4:00pm @larrybabb to present this (Kelsea is in that day but will likely be heading to the airport at that time)
- [ ] Finalizing the model with feedback from Broad Weekly Meeting incorporated 

**DoD:** Having a model of what each discrepancy report should look like with minimal information required. As each specific report is developed, data specific to that audience (VCEPs, GC, Labs) will be incorporated, but this model report will have all of the fundamental tabs, filters, data, etc that each report will universally contain.

**Comment by larrybabb** [comment]
premature. not needed.

**Comment by dazzariti** [comment]
Closing, old out of date ticket
