### ISSUE TITLE
Tracking CvC annotations by VCV and SCV versions

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-curation-input-tool#49]
Discussed on January 13th CvC User Meeting

In ClinVar Reports - it would be helpful to highlight (color change etc.) if the CvC annotation is on a different version than the most recent version

**Comment by larrybabb** [comment]
review with Heidi on Monday's call.

**Comment by dazzariti** [comment]
I don't think this is needed any longer, and if needed, a more specific ticket should be created.
