### ISSUE TITLE
Refreshing "CvC" curated dataset/archiving historic CvC Annotation dataset

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-curation-input-tool#66]
Based on September 5th CvC Meeting discussion

-Export/download all the data from the CVC annotations sheet [CvCuration Annotations] (done) (https://docs.google.com/spreadsheets/d/1pzuWR409vSmoFX9inmoU6el6vjG0SniB1KrxWLeVpaA/edit#gid=1495804276)

- Once a backup is created, keep the following 1) everything Heidi has annotated 2) all 163 Non Contributory annotations submitted to ClinVar and 3) anything Julie has done since she has been fully trained (as of date June 5, 2023)

Of the pilot variants submitted to ClinVar, remove "Notes" from all but the SCVs except:

Color
SCV001734358
SCV001735003
SCV001736607
And LMM has 1: SCV000208727
Invitae has 4:
SCV000948007
SCV001195236
SCV001570788
SCV002125915
Illumina has 6:
SCV000348823
SCV000363545
SCV000363579
SCV000363580
SCV000363525
SCV000363526

**Comment by dazzariti** [comment]
@RyanFWebb @larrybabb 

I added this from our conversation yesterday, please update if I captured anything wrong. I added this to the SCV ext repo since this is about the extension output - hopefully that makes sense!

**Comment by RyanFWebb** [comment]
@dazzariti I've deleted all of the notes except for those specified by Heidi and added a historical sheet called "SCV Records with Notes". Do we want the historical sheet to be a separate document?

**Comment by dazzariti** [comment]
@RyanFWebb Following up on discussion today with Larry, any "Follow Up" tags or VCV annotations should be archived as well if remaining in the [CvCuration Annotations](https://docs.google.com/spreadsheets/d/1pzuWR409vSmoFX9inmoU6el6vjG0SniB1KrxWLeVpaA/edit#gid=1495804276) sheet after you archived the other categories above

**Comment by dazzariti** [comment]
@RyanFWebb we discussed at the standup this was probably close to done, so we ranked at the top of your priority list. If you have any questions for me and Larry just send our way.

**Comment by RyanFWebb** [comment]
This request is complete.

**Comment by RyanFWebb** [comment]
This has been completed in the CvCuration Annotations spreadsheet on the "Refilter" sheet. Records reviewed by Julie before 6/5/2023 that were retired after that date have been left in for now as well as records reviewed by others (not Julie or Heidi) if the SCV was part of the ClinVar submission. Let me know if either of these selections needs to be adjusted.

**Comment by dazzariti** [comment]
@larrybabb I've reviewed with @RyanFWebb, this is in good shape, but will need final review with you

**Comment by larrybabb** [comment]
I've taken a look and would like to get more clarity on exactly which records we are keeping

We are keeping ...
1. all of Julie's curations on and after 6/5/2023
2. all curations used in the clinvar submission in early September (currently in progress)
3. all of Heidi's curations

Question: are we keeping any other curations (e.g. those not from Heidi or Julie)?

@dazzariti or @RyanFWebb  can you verify or clarify my understanding of what the plan was?

**Comment by RyanFWebb** [comment]
Need to remove records from Julie that were annotated before 6/5 but retired afterwards.
