### ISSUE TITLE
In the chrome extension change 'non-contributory' to 'flagging candidate'

### ISSUE THREAD

**Issue by PamRobertson** [clingen-data-model/clinvar-curation-input-tool#68]
As discussed in our CvC meeting (10/31/23) update the chrome extension to have the option 'flagging candidate' instead of 'non-contributory'. @dazzariti @larrybabb @RyanFWebb

**Comment by larrybabb** [comment]
@dazzariti and/or Pam 
Please install and verify that the flagged candidation option is now working as required by this ticket. If all is fine, feel free to close this ticket. You can install the new version here --> https://github.com/clingen-data-model/clinvar-curation-input-tool/releases/tag/1.10
