### ISSUE TITLE
Update chrome extension to allow multiple options (outlier, old, insufficient evidence)

### ISSUE THREAD

**Issue by PamRobertson** [clingen-data-model/clinvar-curation-input-tool#75]
As discussed on Feb 6th call, update chrome extension to allow multiple options (outlier, old, insufficient evidence). 
@dazzariti @larrybabb @RyanFWebb

**Comment by dazzariti** [comment]
Discuss on April 12th call - this request is still needed  - but rather than allowing multiple options, Larry will just add new combinations of choices

@jratliff1234 Please review the list of Reasons and list the combinations you'd like here

**Comment by dazzariti** [comment]
Decision from May 20th call - add an additional option

"Older and outlier claim with insufficient supporting evidence"

**Comment by dazzariti** [comment]
@larrybabb @PamRobertson 

My understanding is based on today's discussion this ticket can be closed  after "Older and outlier claim with insufficient supporting evidence" is added as a Flagging Candidate reason

Based on the Slack discussion, it appears this is complete, so I'm closing the issue
