### ISSUE TITLE
Creating a new reason for the discordance project in the chrome extension

### ISSUE THREAD

**Issue by PamRobertson** [clingen-data-model/clinvar-curation-input-tool#89]
Discussed in the CvC meeting (Oct 28th) that there is high number of flagged SCVs with 'Other' as the reason due to the discordance project. Therefore we decided to create a new reason 'P/LP classification for a variant in a gene with insufficient evidence for a gene-disease relationship' under 'Old/Outlier/Unsupported Submissions' rather than 'Other'. 

The decision path will look like this:
Flagging candidate > Old/Outlier/Unsupported Submissions > P/LP classification for a variant in a gene with insufficient evidence for a gene-disease relationship

@larrybabb @dazzariti

**Comment by larrybabb** [comment]
fixed in release 1.16 and PR #91
