### ISSUE TITLE
Creating a new Action drop down 'Remove Flagged Submission'

### ISSUE THREAD

**Issue by PamRobertson** [clingen-data-model/clinvar-curation-input-tool#90]
As discussed in our CvC meeting (11/18/24) and over Slack, Larry will create an extra Action drop down option in the chrome extension called 'Remove Flagged Submission'. This will require a Reason before it can be submitted. The discussed reasons will be:
- Other SCVs submitted for VCV record 
- Gene-disease relationship classification has changed
- Discussion with submitter
- Curation error
- Other (and then the curator will need to manually add this other reason in the notes)

@dazzariti @larrybabb

**Comment by larrybabb** [comment]
fixed in release 1.16 and PR #91 91
